/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import models.Customer;

/**
 *
 * @author 30471297
 */
public class Confirmation extends javax.swing.JPanel {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Confirmation.class.getName());    
    private Customer loggedInCustomer;// fix imports
    /**
     * Creates new form Confirmation
     */
    public Confirmation(Customer c) {
        loggedInCustomer = c;
        initComponents();
        
    }
    
    //lblOrderPlaced.setText("Order Placed!");   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturnToCustomerHome = new javax.swing.JButton();
        lblOrderPlaced = new javax.swing.JLabel();

        btnReturnToCustomerHome.setText("Return To Customer Home");
        btnReturnToCustomerHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToCustomerHomeActionPerformed(evt);
            }
        });

        lblOrderPlaced.setText("Order Placed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReturnToCustomerHome)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblOrderPlaced)
                        .addGap(179, 179, 179))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(lblOrderPlaced)
                .addGap(60, 60, 60)
                .addComponent(btnReturnToCustomerHome)
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnToCustomerHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToCustomerHomeActionPerformed
        // Assessment 8
        //Customer_Home chome = new Customer_Home(loggedInCustomer);
        Customer_Home chome = new Customer_Home(loggedInCustomer);
        chome.setVisible(true);   
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnToCustomerHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnToCustomerHome;
    private javax.swing.JLabel lblOrderPlaced;
    // End of variables declaration//GEN-END:variables
}
