/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import models.DBManager;
import models.HeatPump;
import models.Product;
import models.SolarPanel;

/**
 *
 * @author 30471297
 */
public class EditProductDetails extends javax.swing.JFrame {
   

    // Logger for runtime issues 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditProductDetails.class.getName());
    private Product productToEdit; //passed in to edit
    /**
     * Creates new form EditProduct
     */
     // Constructor. Receives the Product to be edited and pre-populates the form
    public EditProductDetails(Product p) {
        getContentPane().setBackground(new Color(153,255,204));//Set background color
        productToEdit = p;// Save reference to the product to edit
        initComponents();
        // the text fields with the existing product details
        txtProductID.setText(String.valueOf(productToEdit.getProductId()));
        txtProductName.setText(String.valueOf(productToEdit.getProductName()));
        txtPrice.setText(String.valueOf(productToEdit.getPrice()));
        txtStockLevel.setText(String.valueOf(productToEdit.getStockLevel()));
        //txtAdditional.setText(String.valueOf(productToEdit.getAdditional()));
        
        if(productToEdit.getClass().getName().equals("models.HeatPump"))// Cast to HeatPump to access its specific attribute
        {
            HeatPump h = (HeatPump)productToEdit;
            
            lblAdditional.setText("EfficiencyRating:");
            txtAdditional.setText(String.valueOf(h.getEfficiencyRating()));//uses HeatPump getter
        //Create getefficiencyRating inside HeatPump class
        }
        else if(productToEdit.getClass().getName().equals("models.SolarPanel"))
        // Cast to SolarPanel to access its specific attribute
        {
            SolarPanel s = (SolarPanel)productToEdit;
            
            lblAdditional.setText("WattageOutput:");
            txtAdditional.setText(String.valueOf(s.getWattageOutput()));//uses SolarPanel getter
            //Create getWattageOutput inside SolarPanel class
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEditProductDetails = new javax.swing.JLabel();
        lblProductID = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblStockLevel = new javax.swing.JLabel();
        lblAdditional = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnReturnToSelectProduct = new javax.swing.JButton();
        txtProductID = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtAdditional = new javax.swing.JTextField();
        txtStockLevel = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEditProductDetails.setForeground(new java.awt.Color(102, 102, 102));
        lblEditProductDetails.setText("Edit Product Details");

        lblProductID.setText("Product ID");

        lblProductName.setText("Name");

        lblStockLevel.setText("StockLevel");

        lblAdditional.setText("Additional");

        btnSubmit.setBackground(new java.awt.Color(204, 255, 204));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnReturnToSelectProduct.setBackground(new java.awt.Color(0, 204, 204));
        btnReturnToSelectProduct.setText("RETURN TO SELECT PRODUCT");
        btnReturnToSelectProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToSelectProductActionPerformed(evt);
            }
        });

        lblPrice.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblStockLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAdditional, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReturnToSelectProduct)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdditional, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEditProductDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblEditProductDetails)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProductName)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrice)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAdditional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReturnToSelectProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStockLevel)
                        .addGap(29, 29, 29)
                        .addComponent(lblAdditional)
                        .addGap(96, 96, 96))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnToSelectProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToSelectProductActionPerformed

        Staff_ProductMenuPage s = new Staff_ProductMenuPage();
        
        s.setVisible(true);
        this.setVisible(false);        
        
    }//GEN-LAST:event_btnReturnToSelectProductActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

     String productName = txtProductName.getText();
     double price = Double.parseDouble(txtPrice.getText());
     int stockLevel = Integer.parseInt(txtStockLevel.getText());
     //boolean availability = Boolean.parseBoolean(txtAvailability.getText());
    // String additional = txtAdditional.getText();
     
     //Create Setters inside Product
     
     productToEdit.setProductName(productName);
     productToEdit.setPrice(price);
     productToEdit.setStockLevel(stockLevel);
    // productToEdit.setAdditional(additional);
 
     
    if(productToEdit.getClass().getName().equals("models.HeatPump"))
        {
            HeatPump h = (HeatPump)productToEdit;
            double efficiencyRating = Double.parseDouble(txtAdditional.getText());
            h.setEfficiencyRating(efficiencyRating);  //create set efficiencyRating in HeatPump

            
            DBManager db = new DBManager();
            db.editProduct(h);
            
        }
 
        else if(productToEdit.getClass().getName().equals("models.SolarPanel"))
        {
            SolarPanel s = (SolarPanel)productToEdit;
            int wattageOutput = Integer.parseInt(txtAdditional.getText());
            s.setWattageOutputIn(wattageOutput);  //create set WattageOutput in SolarPanel

            
            DBManager db = new DBManager();
            db.editProduct(s);               

        }     
    
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(() -> new EditProductDetails().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnToSelectProduct;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblAdditional;
    private javax.swing.JLabel lblEditProductDetails;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblStockLevel;
    private javax.swing.JTextField txtAdditional;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtStockLevel;
    // End of variables declaration//GEN-END:variables
}
