/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import models.DBManager;
import models.Product;

/**
 *
 * @author 30471297
 */
public class SearchSortProducts extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchSortProducts.class.getName());
    
    private DefaultListModel <String> model= new DefaultListModel<>();
    
    private ArrayList<Product> products = new ArrayList<>();
    
    /**
     * Creates new form SearchSortProductss
     */
    public SearchSortProducts() {
        initComponents();
        
        lstProducts.setModel(model);
        
        loadAllProducts();
        displayProducts();
    }

    private void loadAllProducts() {
        DBManager db = new DBManager(); // fix imports
        products = db.loadProducts();
        
    }
    
    private void bubbleSortProducts(){
        int totalProducts = products.size();

    for (int pass = 0; pass < totalProducts - 1; pass++) {
        boolean didSwap = false;

        for (int index = 0; index < totalProducts - pass - 1; index++) {
            if (products.get(index).getPrice() > products.get(index + 1).getPrice()) {
                // Swap the products
                Product currentProduct = products.get(index);
                products.set(index, products.get(index + 1));
                products.set(index + 1, currentProduct);
                didSwap = true;
            }
        }

        // Stop early if no swaps occurred
        if (!didSwap)
            break;
    }
    }
    
    // Method: Selection Sort in Ascending Order by Product Price
    private void sortProductsByPriceAscending() {
    int totalProducts = products.size();

    // Loop through each product except the last one
    for (int currentIndex = 0; currentIndex < totalProducts - 1; currentIndex++) {
        int lowestPriceIndex = currentIndex;

        // Find the product with the lowest price in the remaining list
        for (int compareIndex = currentIndex + 1; compareIndex < totalProducts; compareIndex++) {
            if (products.get(compareIndex).getPrice() < products.get(lowestPriceIndex).getPrice()) {
                lowestPriceIndex = compareIndex;
            }
        }

        // Swap the current product with the product that has the lowest price
        if (lowestPriceIndex != currentIndex) {
            Product tempProduct = products.get(currentIndex);
            products.set(currentIndex, products.get(lowestPriceIndex));
            products.set(lowestPriceIndex, tempProduct);
        }
    }
}

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBubbleSort = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProducts = new javax.swing.JList<>();
        btnSelectionSort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBubbleSort.setText("Bubble Sort");
        btnBubbleSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBubbleSortActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstProducts);

        btnSelectionSort.setText("Selection Sort");
        btnSelectionSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectionSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBubbleSort)
                        .addGap(57, 57, 57)
                        .addComponent(btnSelectionSort)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBubbleSort)
                    .addComponent(btnSelectionSort))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBubbleSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBubbleSortActionPerformed
    //stage 12
    
    bubbleSortProducts();
    displayProducts();
    
    }                                             
    
    private void displayProducts()
    {
        model.clear();
        for(Product p: products)
        {
            model.addElement(p.getProductName() + " -£" +p.getPrice());
        }
    
    }//GEN-LAST:event_btnBubbleSortActionPerformed

    private void btnSelectionSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectionSortActionPerformed
    // stage 13
    
     sortProductsByPriceAscending();
     displayProducts();
     // btnBinarySearch.setEnabled(true);


    
    }//GEN-LAST:event_btnSelectionSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchSortProducts().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBubbleSort;
    private javax.swing.JButton btnSelectionSort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstProducts;
    // End of variables declaration//GEN-END:variables
}
