/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import javax.swing.DefaultListModel;
import models.Customer;

/**
 *
 * @author 30471297
 */
public class SelectPaymentMethod extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SelectPaymentMethod.class.getName());
    private Customer loggedInCustomer; //Holds the currently logged-in customer
    /**
     * Creates new form SelectPaymentMethod
     */
    //Constructor: receives the logged-in customer and sets up the UI.
    public SelectPaymentMethod(Customer c) {
        loggedInCustomer = c;//save customer reference
        getContentPane().setBackground(new Color(153,255,204));
        initComponents();
    }
        public void show_all_cardNumbers()
    {
        DefaultListModel cardModel = new DefaultListModel();
        // Loop through card numbers stored in the customer object
        for(int card :loggedInCustomer.getCardNumbers())            
        {
         cardModel.addElement(card);  
        }
        // Display card numbers in the list
        lstCardNumbers.setModel(cardModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectPaymentMethod = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCardNumbers = new javax.swing.JList<>();
        lblCard = new javax.swing.JLabel();
        txtNewCard = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblConfirmation = new javax.swing.JLabel();
        btnConfirmPaymentMethod = new javax.swing.JButton();
        lblDefaultCard = new javax.swing.JLabel();
        txtDefaultCard = new javax.swing.JTextField();
        btnAddDefaultCard = new javax.swing.JButton();
        btnDeleteSelecterdCard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSelectPaymentMethod.setForeground(new java.awt.Color(102, 102, 102));
        lblSelectPaymentMethod.setText("Select Payment Method");

        btnDelete.setBackground(new java.awt.Color(0, 204, 204));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lstCardNumbers.setBackground(new java.awt.Color(204, 255, 204));
        jScrollPane1.setViewportView(lstCardNumbers);

        lblCard.setText("New Card");

        btnAdd.setBackground(new java.awt.Color(255, 255, 204));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblConfirmation.setForeground(new java.awt.Color(102, 102, 102));
        lblConfirmation.setText("Confirm Payment Method");

        btnConfirmPaymentMethod.setBackground(new java.awt.Color(204, 255, 255));
        btnConfirmPaymentMethod.setText("Confirm Payment Method");
        btnConfirmPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmPaymentMethodActionPerformed(evt);
            }
        });

        lblDefaultCard.setBackground(new java.awt.Color(255, 255, 204));
        lblDefaultCard.setText("Default Payment Method");

        btnAddDefaultCard.setBackground(new java.awt.Color(255, 255, 204));
        btnAddDefaultCard.setText("ADD");
        btnAddDefaultCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDefaultCardActionPerformed(evt);
            }
        });

        btnDeleteSelecterdCard.setBackground(new java.awt.Color(204, 255, 255));
        btnDeleteSelecterdCard.setText("Delete Selected Card");
        btnDeleteSelecterdCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSelecterdCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmPaymentMethod)
                    .addComponent(lblConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDefaultCard)
                            .addComponent(txtNewCard)
                            .addComponent(lblCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDefaultCard, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddDefaultCard)
                            .addComponent(btnDeleteSelecterdCard, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(lblSelectPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblSelectPaymentMethod)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNewCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDefaultCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDefaultCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnAddDefaultCard)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmPaymentMethod)
                        .addGap(34, 34, 34)
                        .addComponent(lblConfirmation)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnDeleteSelecterdCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnDelete)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Removes the selected card from the customer's list by index.
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Ensure user selected a card first
        if (lstCardNumbers.getSelectedIndex() == -1)
        {
            lblConfirmation.setText("Error: Select Card before Deleting");
        }
        else
        {
            // Remove card by index
            loggedInCustomer.removeCard(lstCardNumbers.getSelectedIndex());
            lblConfirmation.setText("Card removed");
            show_all_cardNumbers();

        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    //Adds a new card number typed in txtNewCard into the customer's card list.
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int NewCard = Integer.parseInt(txtNewCard.getText());//convert input to int
   
        loggedInCustomer.addNewCard(NewCard); // add card
       
        lblConfirmation.setText("New Card Added");

        show_all_cardNumbers();

    }//GEN-LAST:event_btnAddActionPerformed
    //Moves user to Confirmation screen, passing the logged-in customer's details.
    private void btnConfirmPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmPaymentMethodActionPerformed
        Confirmation confirm = new Confirmation(loggedInCustomer);
        confirm.setVisible(true);
        this.setVisible(false);// hide this window
    }//GEN-LAST:event_btnConfirmPaymentMethodActionPerformed
    // Stores a card number as part of the customer’s card list.
    private void btnAddDefaultCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDefaultCardActionPerformed
        int newCard = Integer.parseInt(txtDefaultCard.getText());
        // add card to the beginning of the LinkedList
        loggedInCustomer.addFirstCard(newCard);
        lblConfirmation.setText("New Card Added");

        show_all_cardNumbers();
    }//GEN-LAST:event_btnAddDefaultCardActionPerformed

    private void btnDeleteSelecterdCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSelecterdCardActionPerformed
    int newCard = Integer.parseInt(txtDefaultCard.getText());
    
    loggedInCustomer.addNewCard(newCard);
    lblConfirmation.setText("New Card Added");

    show_all_cardNumbers();
    }//GEN-LAST:event_btnDeleteSelecterdCardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new SelectPaymentMethod().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddDefaultCard;
    private javax.swing.JButton btnConfirmPaymentMethod;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteSelecterdCard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCard;
    private javax.swing.JLabel lblConfirmation;
    private javax.swing.JLabel lblDefaultCard;
    private javax.swing.JLabel lblSelectPaymentMethod;
    private javax.swing.JList<String> lstCardNumbers;
    private javax.swing.JTextField txtDefaultCard;
    private javax.swing.JTextField txtNewCard;
    // End of variables declaration//GEN-END:variables
}
