/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import views.MainMenu;

/**
 *
 * @author 30471297
 */
public class Staff_Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Staff_Home.class.getName());

    /**
     * Creates new form StaffHome
     */
    public Staff_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModifyProducts = new javax.swing.JButton();
        btnViewAllOrders = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnSearchAndSortProducts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnModifyProducts.setBackground(new java.awt.Color(255, 255, 204));
        btnModifyProducts.setText("Modify Products");
        btnModifyProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyProductsActionPerformed(evt);
            }
        });

        btnViewAllOrders.setBackground(new java.awt.Color(255, 255, 204));
        btnViewAllOrders.setText("View All Orders");

        btnLogOut.setBackground(new java.awt.Color(0, 204, 204));
        btnLogOut.setText("LOGOUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnSearchAndSortProducts.setBackground(new java.awt.Color(255, 255, 204));
        btnSearchAndSortProducts.setText("Search And Sort Products ");
        btnSearchAndSortProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAndSortProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewAllOrders)
                            .addComponent(btnModifyProducts)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnSearchAndSortProducts)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnModifyProducts)
                .addGap(35, 35, 35)
                .addComponent(btnSearchAndSortProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnViewAllOrders)
                .addGap(27, 27, 27)
                .addComponent(btnLogOut)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
    MainMenu mMenu = new MainMenu();
    mMenu.setVisible(true);
    this.setVisible(false);      
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnModifyProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyProductsActionPerformed

        Staff_ProductMenuPage sStaff_ProductMenuPage = new Staff_ProductMenuPage();
        
        //get visible the new frame
        sStaff_ProductMenuPage.setVisible(true);
        // hide the current frame
        this.setVisible(false);
    }//GEN-LAST:event_btnModifyProductsActionPerformed

    private void btnSearchAndSortProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAndSortProductsActionPerformed
    // stage 12
    
    SearchSortProducts sersorp = new SearchSortProducts();
    sersorp.setVisible(true);
    this.setVisible(false);
    
    }//GEN-LAST:event_btnSearchAndSortProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Staff_Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnModifyProducts;
    private javax.swing.JButton btnSearchAndSortProducts;
    private javax.swing.JButton btnViewAllOrders;
    // End of variables declaration//GEN-END:variables
}
